name: docker pr

on:
  push:

env:
  IMAGE_FQDN: ghcr.io/jodconverter/jodconverter-runtime

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Build JRE
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false
          target: jre
          tags: |
            ${{ env.IMAGE_FQDN }}:latest
      - name: Build JDK
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false
          target: jre
          tags: |
            ${{ env.IMAGE_FQDN }}:jdk-latest
      - name: Push JRE
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: jre
          tags: |
            ${{ env.IMAGE_FQDN }}:latest
            ${{ env.IMAGE_FQDN }}:${{ github.ref_name }}
      - name: Push JDK
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: .
          platforms: linux/amd64
          push: true
          target: jdk
          tags: |
            ${{ env.IMAGE_FQDN }}:jdk-latest
            ${{ env.IMAGE_FQDN }}:jdk-${{ github.ref_name }}
